### ISSUE TITLE
Sleep data not imported on OnePlus 7T Pro and others, but works fine on Moto G7

### ISSUE THREAD

**Issue by kamilryszkowski** [StasDoskalenko/react-native-google-fit#175]
I'm trying to import sleep data via activity samples, my code looks more or less like this:

```
GoogleFit.getActivitySamples(options, (err, res) => {
  const sleepData = res.filter(item => item.activityName === 'sleep')
  resolve(sleepData)
})
```
I received reports from some of my users that the import doesn't work, i.e. data that is in Google Fit is not showing up in my app. Several of them are syncing data into Google Fit from apps like Sleep as Android or devices like Mi Fit, whereas others are typing it in manually.

I myself have two phones. One is Moto G7, in which sleep entries added manually into Google Fit show up correctly. The other is OnePlus 7T Pro, for which manual entries from Google Fit don't show up at all. In both, I am logged into the same Gmail account.

How can I go about debugging this and making sure that what I import reflects what shows in Google Fit for all devices?

**Comment by aboveyunhai** [comment]
hmm, there is sleep function for retrieving sleep data only , are you able to get anything from it? 
I just take a look at the `getActivitySamples` function, it actually has nothing to do with sleep data, I am a little bit of surprise you can get sleep data from it.

**Comment by kamilryszkowski** [comment]
Thanks for your reply @aboveyunhai 
What is the proper way of getting sleep? There is nothing in the readme except point 8 about activities, referring to https://developers.google.com/fit/rest/v1/reference/activity-types with the full list (including sleep). As I said, it works on my Moto G7 and for many of my users.

**Comment by aboveyunhai** [comment]
@kamilryszkowski  does other data work except sleep data? If others are also not working then it might be a device issue.
you can try this to see if you can get any data from it? if so then might be a bug in `getActivitySamples`
`GoogleFit.getSleepData(options, (err, res) => {
  const sleepData = res.filter(item => item.activityName === 'sleep')
  resolve(sleepData)
})`

**Comment by kamilryszkowski** [comment]
@aboveyunhai - my app also fetches steps, blood pressure, heart rate and weight; they all work fine.

I wasn't aware about getSleepData actually, it's not in the README but I can see its code in index.android.js. I tried using it right next to my other functions that all work (which should mean that I have all the authorisation needed), but I'm getting the following message in response: `4: The user must be signed in to make this API call.` and no data.

My scopes are:
```
Scopes.FITNESS_ACTIVITY_READ_WRITE,
Scopes.FITNESS_BODY_READ_WRITE,
Scopes.FITNESS_LOCATION_READ,
Scopes.FITNESS_BLOOD_PRESSURE_READ,
```

Anything else that I need to do to get getSleepData to work? 

If it matters, I had to use the solution from https://github.com/StasDoskalenko/react-native-google-fit/issues/176#issuecomment-671872879 to get the app to compile in the last few days.

**Comment by aboveyunhai** [comment]
@kamilryszkowski https://github.com/StasDoskalenko/react-native-google-fit/issues/176#issuecomment-673070038
I believe you need to `sign out and sign in` again from the current account. According to https://github.com/StasDoskalenko/react-native-google-fit/issues/176#issuecomment-674073196, I guess the problem comes from the Api upgrades. 
V10 uses deprecated API and V13 use the standard API (for step fetching only, but I think we should upgrade all the other deprecated apis eventually in case google make change again like this time). So you get the error even though when your account is signed in but did not subscribe to the service.  
If it works out, I'm not exactly sure how to handle production build for this change, whether notify your users to re-sign in manually or try to catch this error and immediately trig `Googlefit.disconnect()` then `connect()` to enforce the process smoothly.

**Comment by kamilryszkowski** [comment]
Thanks a lot for your help @davidguerrerolopez and @aboveyunhai 

I updated to 0.14.1, in which the inclusion of #187 has fixed the `(...) API call` permission issue; `getSleepData()` is now working well. If there are still issues faced by my users that I can't resolve I'll report back, but meanwhile closing.
