### ISSUE TITLE
Where to find these to download? 

### ISSUE THREAD

**Issue by StevenTong12** [StasDoskalenko/react-native-google-fit#218]
> Android Support Repository
> Android Support Library
> Google Play services
> Google Repository
> Google Play APK Expansion Library 

I'm having a hard time finding how to download these via Android Studio, can anyone help? Also, could not having these be the reason why when I check the authorization it returns false always?

**Comment by aboveyunhai** [comment]
I believe your question is more relate to the virtual machine setup in Android Studio. 
I don't know how to answer the question since there are not part of this libs but you may get the idea from these links.
https://developer.android.com/studio/run/managing-avds
https://reactnative.dev/docs/environment-setup

Failed authentication usually means something wrong from your Google Authentication process. There are a lot of opened/closed issues related to it so you might take a look at them.
