### ISSUE TITLE
Samsung support?

### ISSUE THREAD

**Issue by Dubask** [StasDoskalenko/react-native-google-fit#244]
Hello,
We managed to use this library, but it seems that we get an error of "device no supported" for Samsung (currently tested on Samsung galaxy note 4)

Is it a known issue, or there is a solution?

Thanks

**Comment by aboveyunhai** [comment]
May I know the system specs for Samsung galaxy note 4?
I assume it's not working because of the android system instead of the hardware itself.
The problem of recent feature implementation is that parts of codes are no longer support old devices (I assume below android **7.0** ).,
which involves (https://developer.android.com/studio/releases/platforms#7.0). The part of codes were directly from Google Documentation. Google is gradually pushing the bottom line.
Unless someone twist those codes into Backward compatibility (I had tried but without success, they behavior differently and mess the fitness storage, api code deprecation issues)

To give you an idea, I have a old HTC ONE m7, which only has android 5.1: Lollipop. I don't expect it's going to work with this lib
