### ISSUE TITLE
Get the oldest available data?

### ISSUE THREAD

**Issue by shmkane** [StasDoskalenko/react-native-google-fit#257]
Is there a way to get the date of the oldest available data in google fit? 

With some Apple health kit packages, you can set the start date to 1970 and end date to today, and limit the results to just 1 - Meaning it will return after the first result is found. Is there some similar workaround?

**Comment by aboveyunhai** [comment]
interesting question, 
Based on this one
https://developers.google.com/android/reference/com/google/android/gms/fitness/request/DataReadRequest.Builder#setLimit(int)

it look like a definitely yes with a lot of flexibilities, but need to test out if it really works.

**Comment by shmkane** [comment]
Furthermore, I'd love to contribute to this project, however I'm not sure how to get a working local copy of this repo. Aside from the [contribution](https://github.com/StasDoskalenko/react-native-google-fit/projects/1) doc, is there anywhere else I can find info?

**Comment by aboveyunhai** [comment]
@shmkane  1970 is the bottom-line timestamp for Google Fit Api. If you called less than that, you will get an app crush without error handler. 

So I think the `enableServerQueries()` is to deal with `unsync` history across multiple devices instead of `you can't read more than a certain timeframe back` as long as it exists in server related to that account. But this indeed points out we need to do some work around from it.

However, `2500-3000` based on my past tests is the rough threshold for a single `DataReadRequest`, which mean if your app risks to do a `relative wide range request` (5 years with 1 day bucket) or (1 hour with 1s bucket), you might stuck even crush your app 
because the amount of data excesses the threshold, assume if you get perfect 3600 data entries from that particular hour.

So for your naïve solution, I felt like it might just be slow, it could be faster if we can use bucket. 

Unfortunately `setLimit` only takes the latest, and hopefully I missed some doc that can do its reverse operation,  otherwise it's quite annoying to make some workaround.

**Comment by shmkane** [comment]
@aboveyunhai not worried about anything before 1970 😅 

I do want to explicitly ask: heart rate doesn't have an option to bucket right? 

A bit about my setup- I'm using an Apple Watch connected to an iPhone with Google Fit installed. I have a separate Samsung S10 that also has Google Fit installed. The device I'm testing on is the S10. 

You mentioned unsync across multiple devices - I wonder if I'm experiencing this issue because of the devices? 

For example, I know for a fact that I have HR data from my watch going back to 2019, but if I try to query for data from the beginning of September, I get an empty array returned.

**Comment by shmkane** [comment]
To be clear, I can get the past week or so of data. But nothing from the beginning of last month or even before that.

**Comment by pankaj-ag** [comment]
> @aboveyunhai This is borderline a different issue, but after some frustration on getting this sort of functionality to work, I found [this](https://stackoverflow.com/a/37531376/2246652) SO thread that claims that you can't read more than a certain timeframe back. I wasn't sure if this project had support for the mentioned [enableServerQueries()](https://developers.google.com/android/reference/com/google/android/gms/fitness/request/DataReadRequest.Builder.html#enableServerQueries())
> 
> My current naive solution for no-bucket data is start from the year 2000 (could be older... but lets be real who has older data in fit?) and iteratively, month by month, query and check to see if any data exists. Once I find a month that contains data, the first datapoint should be the first data object available...
> 
> However, because I can't look back more than around a couple weeks, I'm stuck.
> 
> Am I approaching this the wrong way?

Did you found a way to enable ServerQueries in this project ?
