### ISSUE TITLE
uploaded the app to the Play Store and I can't. Authentication with Google fit.

### ISSUE THREAD

**Issue by boaracer** [StasDoskalenko/react-native-google-fit#270]
I uploaded the app to the Play Store and I can't. Authentication with Google fit. Only list. When pressed, nothing happens after that. I tested it on Debug. It can be used normally. But why can't I use it when I put it on PlayStore? Or is it about Verification in the OAuth consent screen menu, or is it still a Pending developer action state?

**Comment by aboveyunhai** [comment]
Read this #260 .
and this https://reactnative.dev/docs/signed-apk-android

**Comment by sanjay628** [comment]
I am facing the same issue @StanislavDoskalenko Please update the request and @aboveyunhai  your solution is not working too.

**Comment by boaracer** [comment]
i still stuck this ploblem my google console status is verify but i can't use auth

**Comment by csotiriou** [comment]
@aboveyunhai this solution does not work anymore.

My application is also verified, and I still can't use the library. It works on debug. this was previously working, something happened lately.

**Comment by boaracer** [comment]
it work for me 

1.Check verified in google console Read this https://github.com/StasDoskalenko/react-native-google-fit/issues/260 .
2.Check that release SHA-1 > Use SHA-1 in Google Play Signing (App Signing)

**Comment by csotiriou** [comment]
@boaracer Just verified this myself, and then I saw your comment. Maybe this should be put inside the docs somewhere, although it's not directly related to the framework. Thanks.

**Comment by aboveyunhai** [comment]
I'm not sure how ppl used github issue before they post one, if you take a research or click the `production` label. My comments always mention about the release key is different than your debug key, which originally from a stackoverflow post.

There are a lot of things i can't do about because the complexity comes from Google auth process instead of the lib itself. I really wish their engineers can improve their docs.
Otherwise I felt like I had to write a full tutorials for Google auth at some point (unfortunately I already did for the local test one). 🥲
