### ISSUE TITLE
How to access the access token from GoogleApiClient for connecting with REST Api

### ISSUE THREAD

**Issue by im-aditya** [StasDoskalenko/react-native-google-fit#74]
Hi,

I am trying to fetch the access token on the android device after the user authorise and then send this access token to my backend server so that we can fetch steps data using Google Fit Rest API.

I have tried this code to get the token after the connection is established:

```
// in GoogleFitManager inside **onConnected** callback
GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext.getApplicationContext(), new Scope(Scopes.FITNESS_ACTIVITY_READ));
new RetrieveTokenTask().execute(gsa.getEmail());

// --------------- //
private class RetrieveTokenTask extends AsyncTask<String, Void, String> {

        @Override
        protected String doInBackground(String... params) {
            String token = null;
            String accountName = params[0];
            String scopes = "oauth2:https://www.googleapis.com/auth/fitness.activity.read";
            try {
                token = GoogleAuthUtil.getToken(mActivity.getApplicationContext(), accountName, scopes);
            } catch (IOException e) {
                Log.e(TAG, "IOException");
                Log.e(TAG, e.getMessage());
            } catch (UserRecoverableAuthException e) {
                Log.e(TAG, "User recoverable auth exception");
                Log.e(TAG, e.getMessage());
            } catch (GoogleAuthException e) {
                Log.e(TAG, "Google auth exception");
                Log.e(TAG, e.toString());
            }
            return token;
        }

        @Override
        protected void onPostExecute(String s) {
            super.onPostExecute(s);
            Log.d(TAG, "GOOGLE FIT TOKEN: " + s);
        }
    }
```

My problem is getEmail() is always returning _default-account_ as value (not the actual email address used) which is causing the getToken call to fail. If I hard code account name to my email id then this works and I can access data using the Rest API. But I cannot get the user's email id this way.

Is there anyway to access the email id or the access token from the GoogleApiClient ?

Thanks

**Comment by ilyafriedman** [comment]
I would also like to know this

**Comment by im-aditya** [comment]
@StasDoskalenko : Any help on this ?

**Comment by Dhaval240420** [comment]
hey @im-aditya , Did you get any solution for an email address or access token?
i have same issue like you.

**Comment by im-aditya** [comment]
@Dhaval240420 : Nope

**Comment by patelrushabh** [comment]
Hello @aboveyunhai @StasDoskalenko  Any help on this ?

**Comment by aboveyunhai** [comment]
@patelrushabh Unfortunately, I did try to implement this feature in the past. After going through the entire google android api doc with all the possible hacky ways. It seems like it's simply impossible without the default Signin method and `.requestEmail()` etc. 
 
https://github.com/react-native-community/google-signin <<<=== the default signin package. Then through some ways if we can **SAFELY** share the sign in account from both packages. There are a lot of configs with that package.
https://developers.google.com/identity/sign-in/android/people<<< Then we can simply get all infos through the simple code from this link.

No matter what, it's required or better to completely rewrite the deprecated code to standard api especially the current api connection part , and if possible we can integrate the default sign in, but this simply excess my current abilities, Or hopefully I'm completely wrong and some experts can facepalm me

**Comment by patelrushabh** [comment]
Hey @aboveyunhai thanks for response and suggestion.
 I get user data with the help of https://github.com/react-native-community/google-signin

i use `GoogleSignin.configure()` and signInSilently() method. after google fit authorization.
  ```
getCurrentUserInfo = async () => {
  try {
    const userInfo = await GoogleSignin.signInSilently();
    this.setState({ userInfo });
  } catch (error) {
    if (error.code === statusCodes.SIGN_IN_REQUIRED) {
      // user has not signed in yet
    } else {
      // some other error
    }
  }
};
```

**Comment by aboveyunhai** [comment]
@patelrushabh  Good to hear, if account is already shared by default then probably it's no need to reinvent the wheels. I will try it later

**Comment by aboveyunhai** [comment]
@patelrushabh based on what you mention, I just go through https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInClient,
and successfully implement the `getUserInfo()` from the existing package. So probably we don't need to install other packages just for getting some account info. Just no sure if there is any side effects.

**Comment by aboveyunhai** [comment]
@patelrushabh Probably my last update. Indeed there are some side effects if we don't carefully signin and signout the account from the app, which can lead to some undesired behaviors and bugs. And I will eventually end up reinventing the Signin package in order to solve those edge cases, which it's not my intent and the intent of this packages. So it's better to just use other package to retrieve user info, just don't forget to do signout from both packages.

**Comment by patelrushabh** [comment]
Okay Thank you! @aboveyunhai 
can we stop step counting when user close application with this package ?  I want step counting only when app is in background and open. 

what is use of google fit disconnect() ? does this help me to stop step counting when app is close ??

**Comment by aboveyunhai** [comment]
> Okay Thank you! @aboveyunhai
> can we stop step counting when user close application ? I want step counting only when app is in background and open.
> 
> what is use of google fit disconnect() ? does this help me to stop step counting when app is close ??

It signs out from current account but seems like did not unsubscribe from service subscription if you are using recording api.

**Comment by patelrushabh** [comment]
hii @aboveyunhai are you working on unsubscribe service of recording api ??

**Comment by marlene89** [comment]
Is there any update on this? I need the server auth code for my backend server.

**Comment by Karthiksheety** [comment]
Hi @patelrushabh,

I have tried that calling   GoogleSignin.signInSilently() after selecting email after that I am not getting Userinfo. 

on GoogleSignin.configure() i am giving only webClientid and offlineAccess as false.

can you help me to get userinfo after google fit authorization?

**Comment by patelrushabh** [comment]
@Karthiksheety  have you added scope ? 'https://www.googleapis.com/auth/userinfo.email' , 'https://www.googleapis.com/auth/userinfo.profile'

**Comment by Karthiksheety** [comment]
@patelrushabh i had given https://www.googleapis.com/auth/userinfo.profile on scope.

`await GoogleSignin.configure({
				scopes: ['https://www.googleapis.com/auth/userinfo.profile'], // what API you want to access on behalf of the user, default is email and profile
				webClientId: '287799221164-7gk256hpc5l4c0u52r60q8ram51tgu11.apps.googleusercontent.com', // client ID of type WEB for your server (needed to verify user ID and offline access)
				offlineAccess: false, // if you want to access Google API on behalf of the user FROM YOUR SERVER
			});

			try {
				const userInfo = await GoogleSignin.signInSilently();
				console.log('inside',userInfo)
			} catch (error) {
				if (error.code === statusCodes.SIGN_IN_REQUIRED) {
				// user has not signed in yet
				} else {
				// some other error
				}
			}`

**Comment by patelrushabh** [comment]
@Karthiksheety have you try with adding scope in await GoogleFit.authorize(ScopeOptions) ?

**Comment by aboveyunhai** [comment]
@Karthiksheety  since the question relates to another package, I highly recommend you read through the documentation from that package and the related issues to see how to use that package properly. I used the package successfully in the past without mixing or hacking around two packages. You probably want to find solution in signin package instead of here.

**Comment by aboveyunhai** [comment]
Recently when I try to add some new functionalities, 
I tried to twist some old/deprecated AUTH codes from fewer years ago, 
With the new/standard AUTH implement, I was able to get all the user profile info (email, id, etc.) **but does not include token** with only fewer lines of configs. Most importantly, it can cut down the codebase by 30%. 
So I am going to reopen it. but it may not happen.

**Comment by sash20m** [comment]
@aboveyunhai 

I have a somewhat of a workaround here. But it should work along with GoogleSignIn.
I needed to know the idToken of the google fit user in the app that I am developing because we store that token in db as a anti-cheat system because we need to know if a user uses his friend's google fit account to get the health data and receive rewards from the app.

Because the app also has google sign in, I ended up creating a solution like this: 
```js
const permissions = {
  scopes: [Scopes.FITNESS_ACTIVITY_READ, Scopes.FITNESS_HEART_RATE_READ],
};

const connect = () => {
      // ... some code...
      
      await GoogleFit.disconnect();

      const isSignedIn = await GoogleSignin.isSignedIn();
      if (isSignedIn) {
        await GoogleSignin.signOut();
      }
      await GoogleSignin.signIn(); 

      await GoogleFit.authorize(permissions);

      const idToken = await GoogleFit.getUserToken();
      // store idToken in db...
}     
```
It's not the most fancy solution, but since I know the Google Fit API itself doesn't provide any help, I added a function `getUserToken()` in a local fork of this lib. The function and returns the last signed in account which corresponds to the one connected account from `signin()`. The google-fit library seems to take this account(from googlesignin) and use it for it's functionalities, but if I signout from the account, signin again with another account, the account that the library uses for health data retrieval is the old one, not the new connected one - thus I added the `await GoogleFit.disconnect();` in the beginning so that it always uses the last account logged in googleSignin. I am not sure why it behaves like this, it's somewhat odd... maybe you know better.

There's another odd behavior. If I sing out of googleSignin but not sign in again, then call the `authorize` function, and then call the `getUserToken`, the idToken is null even though the authorize was successful and probably the health data retrieval will be as well. So it's a bit confusing because the GoogleFit library takes in the account from googlesignin, however, if there is no account in googlesignin, it still somehow takes the last one you logged into but the idToken cannot be fetched because it doesn't exist.

I couldn't figure out exactly why it behaves like this but the code above works for me. Every time the user connect to google fit he/she can pick the account and I can save the idToken. You can also get the token from the googleSignin itself via `const { idToken } = await GoogleSignin.signIn();` or with the function I made. I can make a pull request with the functionality and add some info in the docs for people that want to use it and explain the necessity to couple it with the googlesignin library used for auth. Please let me know and as soon as I find some time I'll make the PR, or not make the PR and use the example above but with `idToken` from the googlesignin.
