### ISSUE TITLE
Struggling getting authorize to work for Google Play apps (works fine locally)

### ISSUE THREAD

**Issue by peralmq** [StasDoskalenko/react-native-google-fit#83]
I've been struggling to get `GoogleFit.authorize()` to work for apps submitted to Google Play (it worked fine locally and with `variant=release`). When I use it I get 
1. `{"message":"ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{4a7b231: android.os.BinderProxy@67061c9}, message=null}"}` once in `GoogleFit.onAuthorizeFailure`
2. then nothing. Once Google's auth modal is finished I never receive any more events to neither `onAuthorize` nor `onAuthorizeFailure`.

**Comment by peralmq** [comment]
Turned out I was using the wrong SHA1 hash (and wrong key) in my Google OAuth client. I'm using [Google Play Store's App Signing feature](https://developer.android.com/studio/publish/app-signing#google-play-app-signing) where you have two keys, one for Uploading your APK and another one for App Signing. I was using the info (SHA1 hash) from the Uploading key when I was supposed to use the info from the  App Signing key.

Also, since I'm using [Google Firebase](https://firebase.google.com/) I never generated my Google OAuth client. But that client used the Uploading key.

**Comment by buddhishan** [comment]
Hi @peralmq I am having the same issue. I have created OAuth 2 Client IDs both for debug and release.
My debug version can successfully authorize and get data from the Google FIT API but the release APKs cannot.

 And I am using firebase and have my google-services.json related generated by firebase console. Can you elaborate on how you solved the above problem? Thanks in advance

**Comment by salles-sandro** [comment]
@buddhishan hey man... can you help me? I'm probably having the same issues... but in my case neither the debug nor the release versions are working. Nothing works at all... 

I've gone through all the steps mentioned on the readme ... downloaded the client_secret.json file and put the file inside android/app folder. 

But still no luck... as soon as I call the .authorize method, it gives me that error:

"ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{8974c2: android.os.BinderProxy@8ed6ffd}, message=null}"

The authorization window opens, but when I pick an account, nothing happens.

PS: I also have a google-services.json inside android/app folder with configurations for firebase.

Can you point me into some direction here? I'm lost...

**Comment by peralmq** [comment]
Here are some more details, hope it helps.

1. Create new credentials in [Google API Console](https://console.cloud.google.com/apis/credentials) 
2. Name: "Release" (or whatever you want)
3. Signing-certificate fingerprint: <The SHA1 from your "App signing certificate" in [Google Play Console](https://play.google.com/apps/publish/) /Release management/App signing/ (Important, don't use the Uploading certificate)>
4. Package name: <your package name>
5. Save
6. Download the newly created credentials `.json` file
7. Put the `.json` file in `android/app` folder

That's it!
And make sure you're following the other stuff in the README, like using `BuildConfig.APPLICATION_ID` and that that is the same as `<your package name>`

**Comment by saudahmed** [comment]
@salles-sandro where you able to run debug version. I am getting the same problem as you did. After the authorization screen, I select an account and it gives authentication failure message.

**Comment by StasDoskalenko** [comment]
@saudahmed have you tried example app?

**Comment by saudahmed** [comment]
@StasDoskalenko , in example app what changes we need to make in code. Also I have done expo eject from managed expo project, this means i am running in ejected workspace.

**Comment by nestorLanex2** [comment]
@peralmq 
Got a question, Hopefully you'll be able to see this. 
I have the same setup as yours. Im using firebase as well in my project and 
I found out that google autocreates the Client ID for you, 
I wanted to modify the SHA1 key on the created Client ID but it does not let me.

so I'm trying to follow your steps ([this one](https://github.com/StasDoskalenko/react-native-google-fit/issues/83#issuecomment-466316604) to be precise), and my question would be at the last part of those steps.

Since firebase has its own **google-services.json** and is located on the same directory as what you've mentioned,
could we just download the .json from the newly created clientID with the App Signing Key on the same directory?

**Comment by peralmq** [comment]
@nestorLanex2 It's been a while since I looked at this and our app has grown. 

I did look into this again some year ago though, because we needed to limit the scope of the API Keys that Firebase had auto created for us. For instance they were lacking a lot of Restrictions which made them a security threat (someone could steal the API keys from an installed app and use it to run Google Maps lookups that cost money per request). 

I wrote down my findings on how the different keys fit together. Maybe this will help you too? Sorry if the formatting is strange, just copy pasting from our Notion.

## Answers/Gotchas

> The `google-services` plugin has two main functions:
> 
> 1. Process the `google-services.json` file and produce Android resources that can be used in your application's code. See [[Adding the JSON File](https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file)](https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file) more information.
> 2. Add dependencies for basic libraries required for the services you have enabled. This step requires that you apply the Google Services Gradle plugin in your `app/build.gradle` file, like so:`apply plugin: 'com.google.gms.google-services'`
>     
>     You can see the result of this step by running `./gradlew :app:dependencies`.
>     
> 
> https://developers.google.com/android/guides/google-services-plugin#introduction
> 

Every `client` have their own `oauth_client`
> A Firebase project can have many API keys [`current_key`], but each API key can only be associated with a single Firebase project
https://firebase.google.com/docs/projects/api-keys#create-api-keys
>

client_type probably means 1 Android, 2 iOS, 3 Web

> **API keys for Firebase are different from typical API keys**
> 
> 
> 
> Unlike how API keys are typically used, API keys for Firebase services are not used to control access to backend resources;
> 
> Usually, you need to fastidiously guard API keys (for example, by using a vault service or setting the keys as environment variables); however, API keys for Firebase services are ok to include in code or checked-in config files.
> 
> https://firebase.google.com/docs/projects/api-keys#api-keys-for-firebase-are-different
> 

> API keys are unrestricted by default. Unrestricted keys are insecure because they can be used by anyone from anywhere. For production applications, you should set both [[application restrictions](https://cloud.google.com/docs/authentication/api-keys#adding-application-restrictions)](https://cloud.google.com/docs/authentication/api-keys#adding-application-restrictions) and [[API restrictions](https://cloud.google.com/docs/authentication/api-keys#adding-api-restrictions)](https://cloud.google.com/docs/authentication/api-keys#adding-api-restrictions).

https://cloud.google.com/docs/authentication/api-keys#api_key_restrictions
> 

Google Play AppSigning also generates and uses another process and that will generate it’s own SHA1 and SHA256 fingerprints

> If you are using [[Google Play App Signing](https://support.google.com/googleplay/android-developer/answer/7384423)](https://support.google.com/googleplay/android-developer/answer/7384423) you need to use the SHA1 from google play since Google will replace your release signing key with the one on googles server
https://stackoverflow.com/a/49464848/350195
>

**Comment by peralmq** [comment]
Another gotcha (or I'm not seeing it in what I posted but maybe I missed it), you can attach multiple SHA certificate fingerprints to your Firebase apps. So, maybe this is what you're asking for? https://support.google.com/firebase/answer/9137403

**Comment by nestorLanex2** [comment]
@peralmq 
I appreciate you replying to me regarding this matter.

on my end I did add the SHA1 key from Google Play App Signing portion into the firebase console after I created a separate Oauth 2 Client ID (since editing the pre made Client Id's SHA1 key yields to an error). 
So basically steps 1 - 5 of your [comment](https://github.com/StasDoskalenko/react-native-google-fit/issues/83#issuecomment-1971832218).

So in my firebase for prod, 
it has both the upload key and the signing key as well. 
I then updated the **google-services.json** file, and resubmitted another build.
Unfortunately it didn't fix the problem.

What I did just last night though is to follow steps 6 and 7 (I don't think this was mentioned in any documentation regarding google apis, but please correct me if I'm wrong), 
and just directly saved the .json file from cloud console _alongside_ firebase's **google-services.json** file.

Currently I'm waiting if it solves the issue, 

though I would like to confirm with you if that was also the case on your app with firebase setup?

**Comment by nestorLanex2** [comment]
@peralmq 
Yeah, I figured It would be a long shot being that it's been years since your implementation. 
I appreciate your help though regarding this. 

Unfortunately the steps did not work on our end. 

What's weird though is that when we installed the working **prod apk** and synced from it, 
then deleted that and installed the _playstore build_, somehow the syncing worked. 

But yeah weird occurence. 

Anyhow thanks again for the help @peralmq !

**Comment by nestorLanex2** [comment]
I finally resolved it!

For those who might need this info, 
for those still supporting android APIs 32 and below, 

Please make sure to include the **legacy sha1 key** on the list of sha 1 keys for oauth Signing
<img width="1366" alt="Screenshot 2024-03-05 at 1 01 31 PM" src="https://github.com/StasDoskalenko/react-native-google-fit/assets/146803447/be56482a-f313-45a3-a0f2-23a2badf00d8">
