### ISSUE TITLE
GoogleFit.isEnabled going to false after killing the app

### ISSUE THREAD

**Issue by amarnathsdr** [StasDoskalenko/react-native-google-fit#86]
Hello everyone,

I wanted to know more about the GoogleFit.isEnabled( (error,isEnbaled) => {}); callback function.

When I reload the app and comme back the isEnabled is at true.
but when I kill the app and come back the isEnabled is at false... Why ???

**Comment by amarnathsdr** [comment]
@StasDoskalenko  ?

**Comment by addingama** [comment]
I have the same problem

**Comment by akiladevinda** [comment]
Any updates ? I have same

**Comment by jasondibenedetto** [comment]
@StasDoskalenko Any update on this?

**Comment by RishiAtMiboso** [comment]
I'm facing same problem, any update on this issue? @StasDoskalenko

**Comment by batical** [comment]
same here.

**Comment by aboveyunhai** [comment]
use `checkIsAuthorized` instead of `isEnabled` 
```
 GoogleFit.checkIsAuthorized().then(() => {
        console.log(GoogleFit.isAuthorized) // Then you can simply refer to `GoogleFit.isAuthorized` boolean.
 })
```

**Comment by RishiAtMiboso** [comment]
@aboveyunhai thank you for your feedback but do you have idea why this might happen, because I'm trying to sync data from google fit in background, in this case if isAuthorized is false it will not read data from google fit, can you suggest any solution for that

**Comment by aboveyunhai** [comment]
> @aboveyunhai thank you for your feedback but do you have idea why this might happen, because I'm trying to sync data from google fit in background, in this case if isAuthorized is false it will not read data from google fit, can you suggest any solution for that

Just make an authentication guard before your google fit functions, if true then we do nothing, otherwise we just call authentication again to request permission. The only thing I am not sure is that the permission panel can be opened from background. 

I try to avoid providing any external link but if you really wonder how I handle the auth check, you might want to take a look at this file. This is the app I currently use the debug the lib. 
https://github.com/aboveyunhai/Pedoer/blob/e00b1d874c83bc37d93e54d809e6834dccf78025/src/redux/actions/ActionCreator.tsx#L19

Also change ` var isAuth = GoogleFit.isAuthorized;` to 
```
  await checkIsAuthorized();
  var isAuth = GoogleFit.isAuthorized;
```
Note that there are probably some bugs I missed and it. I only test it **in app** only, after I disconnect from current account and call my google fit function somewhere else, this will trig the regular authentication process.
But you get the idea.

**Comment by RishiAtMiboso** [comment]
@aboveyunhai  thanx for help will try this
